name: "install uv"
description: "Install uv package manager"
runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        python-version: "3.14"
        version: "latest"

